version: '3.9'

services:
  backend:
    container_name: backend-api
    build:
      context: .
    ports:
      - 3001:3001
    environment:
      - APP_PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - DB_NAME=measuresdb
      - DB_HOST=db
      - DB_PORT=3306
    networks:
      - backend-network
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app-backend
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 2s
      retries: 2
    command: npm run start

  db:
    image: mysql:8.0.32
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: measuresdb
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
    restart: 'always'
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 2s
      retries: 2

volumes:
  mysql_data:

networks:
  backend-network:
    driver: bridge