version: '3.9'

services:
  backend:
    container_name: backend-api
    build:
      context: .
    ports:
      - 3001:3001
    environment:
      - APP_PORT=3001
      - DB_USER=root
      - DB_PASS=MYSQL_ROOT_PASSWORD
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run dev

  db:
    image: mysql:8.0.32
    container_name: db
    ports:
      - 3360:3306
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql
    restart: 'always'

volumes:
  mysql_data: